name: Assign to Support Team for Bug Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        uses: cli/cli@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if issue has 'bug' label and assign to support team
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee @OpenSubdomains/support
