name: Assign Team to Issues

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          teams: support
          numOfAssignee: 1
