name: Assign to Support Team for All Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        uses: cli/cli@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Assign the support team to the issue
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee @OpenSubdomains/support
