name: Send Message to PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Send message to the pull request
      - name: Send message to PR
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body": "This is a message sent automatically by the workflow."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
