name: Send PR Message

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send message to PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: upsert
          create-if-not-exists: true
