name: Send Message to PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Send message to the pull request
      - name: Send message to PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world !
