name: PR Validation

on:
  pull_request:
    types:
      - opened

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the domain validation tests
      - name: Run domain validation tests
        run: |
          node tests/domain.test.js
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Domain validation failed."
            exit $exit_code
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
